crypto_ticker:
  build: .
  ports:
  - 5000:5000
  volumes:
  - ./code:/code
  environment:
    API_DEBUG: 'true'
    FROM_CURRENCIES: 'BTC,ETH,BCH,DASH,XRP,XMR,STRAT,LTC,DASH'
    TO_CURRENCIES: 'SEK,EUR,USD'

grafana:
  image: grafana/grafana
  volumes:
  - ./storage/grafana/data:/var/lib/grafana
  - ./storage/grafana/config.ini:/etc/grafana/grafana.ini
  ports:
  - 3000:3000
  links:
  - prometheus:prometheus

prometheus:
  image: prom/prometheus:latest
  links:
  - crypto_ticker:crypto_ticker
  ports:
  - 9090:9090
  volumes:
  - ./storage/prometheus/data:/data
  - ./storage/prometheus/config.yml:/etc/prometheus/prometheus.yml
  command:
  - -storage.local.path=/data
  - -config.file=/etc/prometheus/prometheus.yml
