crypto_ticker:
  image: kallqvist/crypto-ticker
  ports:
  - 5000:5000
  environment:
    API_DEBUG: 'true'
    CRYPTO_FROM: 'BTC,ETH,BCH,DASH,XRP,XMR,STRAT,LTC,DASH'
    CRYPTO_TO: 'EUR,USD'
    FIAT_FROM: 'EUR,USD'
    FIAT_TO: 'SEK'

grafana:
  image: grafana/grafana
  volumes:
  - ./storage/grafana/data:/var/lib/grafana
  - ./config/grafana/config.ini:/etc/grafana/grafana.ini
  ports:
  - 3000:3000
  links:
  - prometheus:prometheus

prometheus:
  image: prom/prometheus:latest
  links:
  - crypto_ticker:crypto_ticker
  ports:
  - 9090:9090
  volumes:
  - ./storage/prometheus/data:/data
  - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
  command:
  - -storage.local.path=/data
  - -config.file=/etc/prometheus/prometheus.yml
